### ISSUE TITLE
Documentation + other usage examples?

### ISSUE THREAD

**Issue by Cyber28** [cloudrex/pocket-db#27]
This looks like an interesting project I would love to use, but there is no documentation (at leas tI couldn't find one) or usage examples of all functions

**Comment by cloudrex** [comment]
This project is not entirely production-ready yet, however I'm planning on working and refining it in the future.

It's in no way abandoned just haven't had time to work on it since I'm currently focusing in other projects, however I have this project under my radar and will get working on it soon!

As for documentation, I'm going to write up some quick docs before next week and entangle everything up so you can try it out.
